include ../config.mk

align.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) align.c -c

check_overlapping_areas.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) check_overlapping_areas.c -c

compute_addresses.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) compute_addresses.c -c

compute_size.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) compute_size.c -c

conv_string.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) conv_string.c -c

def_statement.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) def_statement.c -c

find_labels.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) find_labels.c -c

find_mnemo.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) find_mnemo.c -c

import_symbols.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) import_symbols.c -c

parse_line.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) parse_line.c -c

scopes.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) scopes.c -c
