include config.mk

align.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) align.c -o align.o

check_overlapping_areas.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) check_overlapping_areas.c -o check_overlapping_areas.o

compute_addresses.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) compute_addresses.c -o compute_addresses.o

compute_size.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) compute_size.c -o compute_size.o

conv_string.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) conv_string.c -o conv_string.o

def_statement.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) def_statement.c -o def_statement.o

find_labels.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) find_labels.c -o find_labels.o

find_mnemo.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) find_mnemo.c -o find_mnemo.o

import_symbols.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) import_symbols.c -o import_symbols.o

parse_line.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) parse_line.c -o parse_line.o

scopes.o:
	$(CC) $(CFLAGS) $(DBCFLAGS) scopes.c -o scopes.o
